package com.viu.patronAPP.config;

import com.viu.patronAPP.domain.model.Coords;
import com.viu.patronAPP.infrastructure.out.persistence.entity.mongo.ProvinceEntity;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.province.ProvinceMongoRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;
import java.util.List;

@Configuration
public class ProvinceDataLoader {


    @Bean
    public CommandLineRunner loadProvinces(ProvinceMongoRepository provinceRepository) {
        return args -> {
            provinceRepository.deleteAll();
            List<ProvinceEntity> provinces = Arrays.asList(
                    ProvinceEntity.builder().id("1").name("A Coruña").coords(Coords.builder().latitude(43.3623).longitude(-8.4115).build()).imageUrl("https://viajes.chavetas.es/wp-content/uploads/2019/12/destacadaqueveracoruna-850x453.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("2").name("Albacete").coords(Coords.builder().latitude(38.9943).longitude(-1.8564).build()).imageUrl("https://sabersabor.es/wp-content/uploads/2021/07/Visita-guiada-a-Albacete.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("3").name("Alicante").coords(Coords.builder().latitude(38.3452).longitude(-0.4810).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-alicante.jpg").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("4").name("Almería").coords(Coords.builder().latitude(36.8340).longitude(-2.4637).build()).imageUrl("https://www.servigroup.com/assets/cache/uploads/gallery/proposals/excursiones/que-ver-almeria/1280x720/alcazaba-almeria-1701094733.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("5").name("Ávila").coords(Coords.builder().latitude(40.6566).longitude(-4.6818).build()).imageUrl("https://www.hola.com/horizon/landscape/ca3e997be14f-avila-murallas-panoramica-t.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("6").name("Badajoz").coords(Coords.builder().latitude(38.8794).longitude(-6.9706).build()).imageUrl("https://media.traveler.es/photos/61377022d7c7024f9175ecea/16:9/w_2000,h_1125,c_limit/131678.jpg").autonomousCommunity("Extremadura").build(),
                    ProvinceEntity.builder().id("7").name("Barcelona").coords(Coords.builder().latitude(41.3851).longitude(2.1734).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-barcelona-1.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("8").name("Vizcaya").coords(Coords.builder().latitude(43.2630).longitude(-2.9349).build()).imageUrl("https://media.traveler.es/photos/64f59cd0756c466be81874ab/16:9/w_2560%2Cc_limit/david-vives--AQJPGnTVLE-unsplash.jpg").autonomousCommunity("País Vasco").build(),
                    ProvinceEntity.builder().id("9").name("Burgos").coords(Coords.builder().latitude(42.3439).longitude(-3.6969).build()).imageUrl("https://www.espanafascinante.com/asset/thumbnail,1280,720,center,center/media/espanafascinante/images/2018/07/09/20180709103536242329.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("10").name("Cáceres").coords(Coords.builder().latitude(39.4752).longitude(-6.3722).build()).imageUrl("https://media.timeout.com/images/106012284/750/422/image.jpg").autonomousCommunity("Extremadura").build(),
                    ProvinceEntity.builder().id("11").name("Cádiz").coords(Coords.builder().latitude(36.5271).longitude(-6.2886).build()).imageUrl("https://www.cadizturismo.com/storage/app/media/uploaded-files/p-cadiz_turismo.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("12").name("Castellón").coords(Coords.builder().latitude(39.9864).longitude(-0.0513).build()).imageUrl("https://www.ccsalera.com/wp-content/uploads/2022/11/monumentos-castellon-scaled.jpg").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("13").name("Ceuta").coords(Coords.builder().latitude(35.8893).longitude(-5.3167).build()).imageUrl("https://revistacentinela.es/wp-content/uploads/2018/11/Ceuta-panoramica.jpg").autonomousCommunity("Ceuta").build(),
                    ProvinceEntity.builder().id("14").name("Ciudad Real").coords(Coords.builder().latitude(38.9861).longitude(-3.9275).build()).imageUrl("https://abrasador.com/wp-content/uploads/2021/12/Plaza_Mayor_de_Ciudad_Reak-min-scaled.jpeg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("15").name("Córdoba").coords(Coords.builder().latitude(37.8882).longitude(-4.7794).build()).imageUrl("https://multimedia.andalucia.org/media/C1DF41C3E6EF456A8B4A9B4845C32593/img/7B2A371526454055A71AC38C335E1834/16-20_Puente_Romano_y_Mezquita_de_Cordoba_Cordoba.jpg?responsive").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("16").name("Cuenca").coords(Coords.builder().latitude(40.0704).longitude(-2.1374).build()).imageUrl("https://repositorio.turismocastillalamancha.com/miscelanea/178474/36/2cbf/cuenca.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("17").name("Girona").coords(Coords.builder().latitude(41.9794).longitude(2.8214).build()).imageUrl("https://mesto-barcelona.cz/data/uploads/girona-opevneni.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("18").name("Granada").coords(Coords.builder().latitude(37.1773).longitude(-3.5986).build()).imageUrl("https://content.r9cdn.net/rimg/dimg/3b/c2/b4c4bfb9-city-27138-55689ae0.jpg?width=1366&height=768&xhint=1902&yhint=1090&crop=true").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("19").name("Guadalajara").coords(Coords.builder().latitude(40.6333).longitude(-3.1636).build()).imageUrl("https://fotos.hoteles.net/articulos/guia-huelva-ciudad-6159-1.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("20").name("Huelva").coords(Coords.builder().latitude(37.2595).longitude(-6.9485).build()).imageUrl("https://media.traveler.es/photos/61376d9070e3cff8b85f8c02/16:9/w_1280,c_limit/139897.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("21").name("Huesca").coords(Coords.builder().latitude(42.1407).longitude(-0.4085).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/huesca-capital.jpg").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("22").name("Jaén").coords(Coords.builder().latitude(37.7647).longitude(-3.7904).build()).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/contenidos-imagenes/viajar/nos-gusta/curiosidades-de-la-catedral-de-la-asuncion-de-jaen/gr-cms-media-featured_images-none-a40e0813-f000-4767-80ca-ccf0d9fc83fb-catedral-jaen-002.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("23").name("Las Palmas").coords(Coords.builder().latitude(28.0994).longitude(-15.4134).build()).imageUrl("https://static-resources.mirai.com/wp-content/uploads/sites/1738/20231117091703/Vistas-Las-Palmas-de-GC.jpg").autonomousCommunity("Canarias").build(),
                    ProvinceEntity.builder().id("24").name("León").coords(Coords.builder().latitude(42.5977).longitude(-5.5671).build()).imageUrl("https://www.spain.info/.content/imagenes/cabeceras-grandes/castilla-leon/leon-plaza-mayor-118901284.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("25").name("Lleida").coords(Coords.builder().latitude(41.6161).longitude(0.6206).build()).imageUrl("https://espanaxdescubrir.com/wp-content/uploads/2021/12/Lleida-2.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("26").name("La Rioja").coords(Coords.builder().latitude(42.4661).longitude(-2.4457).build()).imageUrl("https://s2.ppllstatics.com/larioja/www/multimedia/202201/08/media/cortadas/mercado-principal-kijH-U160483022264mvF-1968x1330@La%20Rioja.jpg").autonomousCommunity("La Rioja").build(),
                    ProvinceEntity.builder().id("27").name("Lugo").coords(Coords.builder().latitude(43.0032).longitude(-7.5582).build()).imageUrl("https://www.spain.info/export/sites/segtur/.content/imagenes/cabeceras-grandes/galicia/lugo-murallas-catedral-s490049140.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("28").name("Madrid").coords(Coords.builder().latitude(40.4168).longitude(-3.7038).build()).imageUrl("https://img.static-kl.com/images/media/65848EF5-2848-4EA7-BE113130180A0A55").autonomousCommunity("Madrid").build(),
                    ProvinceEntity.builder().id("29").name("Málaga").coords(Coords.builder().latitude(36.7203).longitude(-4.4199).build()).imageUrl("https://coeohouse.com/wp-content/uploads/2023/03/17-facts-about-Malaga.jpeg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("30").name("Melilla").coords(Coords.builder().latitude(35.2920).longitude(-2.9381).build()).imageUrl("https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/44/b9/a0/vista-aerea-de-la-ciudad.jpg?w=900&h=500&s=1").autonomousCommunity("Melilla").build(),
                    ProvinceEntity.builder().id("31").name("Murcia").coords(Coords.builder().latitude(37.9844).longitude(-1.1285).build()).imageUrl("https://www.espanaguide.com/images/murcia/calle-traperia-murcia-mobile.jpg").autonomousCommunity("Murcia").build(),
                    ProvinceEntity.builder().id("32").name("Ourense").coords(Coords.builder().latitude(42.3365).longitude(-7.8637).build()).imageUrl("https://www.spain.info/.content/imagenes/cabeceras-grandes/galicia/ourense-galicia-plaza-mayor-177596441-c-rodrigo-garrido-shutterstock.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("33").name("Asturias").coords(Coords.builder().latitude(43.3623).longitude(-5.8494).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-asturias.jpg").autonomousCommunity("Asturias").build(),
                    ProvinceEntity.builder().id("34").name("Palencia").coords(Coords.builder().latitude(42.0078).longitude(-4.5346).build()).imageUrl("https://www.lavanguardia.com/files/og_thumbnail/uploads/2017/06/14/5fa3c84a0b3cd.jpeg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("35").name("Illes Balears").coords(Coords.builder().latitude(39.5711).longitude(2.6518).build()).imageUrl("https://estaticos-cdn.prensaiberica.es/clip/49784cc4-e033-4960-ac35-70b5c2d94565_original-libre-aspect-ratio_default_0.jpg").autonomousCommunity("Illes Balears").build(),
                    ProvinceEntity.builder().id("36").name("Navarra").coords(Coords.builder().latitude(42.8141).longitude(-1.6452).build()).imageUrl("https://turismo.navarra.com/wp-content/uploads/Castillo_Olite_Navarra1.jpg").autonomousCommunity("Navarra").build(),
                    ProvinceEntity.builder().id("37").name("Pontevedra").coords(Coords.builder().latitude(42.4338).longitude(-8.6480).build()).imageUrl("https://www.guiategalicia.com/wp-content/uploads/2017/08/IMG_4716.jpeg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("38").name("Salamanca").coords(Coords.builder().latitude(40.9674).longitude(-5.6654).build()).imageUrl("https://salamanca.es/images/promo_salamanca_40seg.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("39").name("Guipúzcoa").coords(Coords.builder().latitude(43.3172).longitude(-1.9819).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/2024/09/ok-turismo-gipuzkoa.jpg").autonomousCommunity("País Vasco").build(),
                    ProvinceEntity.builder().id("40").name("Santa Cruz De Tenerife").coords(Coords.builder().latitude(28.4629).longitude(-16.2472).build()).imageUrl("https://www.spain.info/export/sites/segtur/.content/imagenes/cabeceras-grandes/canarias/santa-cruz-de-tenerife-s362881445.jpg").autonomousCommunity("Canarias").build(),
                    ProvinceEntity.builder().id("41").name("Cantabria").coords(Coords.builder().latitude(43.1828).longitude(-3.9878).build()).imageUrl("https://lacorujadelebro.com/wp-content/uploads/Cantabria-2-2.jpg").autonomousCommunity("Cantabria").build(),
                    ProvinceEntity.builder().id("42").name("Segovia").coords(Coords.builder().latitude(40.9481).longitude(-4.1187).build()).imageUrl("https://www.turismocastillayleon.com/es/patrimonio-cultura/puentes/acueducto-segovia.ficheros/193170-Acueducto%20de%20Segovia.jpg/g,193170-Acueducto%20de%20Segovia.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("43").name("Sevilla").coords(Coords.builder().latitude(37.3886).longitude(-5.9823).build()).imageUrl("https://img2.rtve.es/v/6864365?w=1600&preview=1681890137650.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("44").name("Soria").coords(Coords.builder().latitude(41.7644).longitude(-2.4633).build()).imageUrl("https://fotografias.lasexta.com/clipping/cmsimages02/2023/03/21/2EAEFC1A-5C54-4ECE-BA02-50AE25063E1C/vista-aerea-soria_default.jpgg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("45").name("Tarragona").coords(Coords.builder().latitude(41.1187).longitude(1.2445).build()).imageUrl("https://content.r9cdn.net/rimg/dimg/8a/55/f710b8f3-city-40385-1717ca7b5af.jpg?width=1200&height=630&xhint=2289&yhint=2332&crop=true").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("46").name("Teruel").coords(Coords.builder().latitude(40.3430).longitude(-1.1062).build()).imageUrl("https://viajes.nationalgeographic.com.es/medio/2018/02/27/teruel__1280x720.jpg").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("47").name("Toledo").coords(Coords.builder().latitude(39.8628).longitude(-4.0273).build()).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/contenidos-imagenes/viajar/vamos-de-excursion/que-ver-toledo/gr-cms-media-featured_images-none-1c489cc1-bf59-4b9d-acec-875c41f2c4fb-01-puente-de-alcantara-vista-general.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("48").name("Valencia").coords(Coords.builder().latitude(39.4699).longitude(-0.3763).build()).imageUrl("https://img.nh-hotels.net/8yYbq/aGoV8/original/Valencia_CAC.jpg?output-quality=70&resize=*:*&background-color=white").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("49").name("Valladolid").coords(Coords.builder().latitude(41.6523).longitude(-4.7282).build()).imageUrl("https://www.cideu.org/wp-content/uploads/2019/12/valladolid-2.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("50").name("Zamora").coords(Coords.builder().latitude(41.5035).longitude(-5.7448).build()).imageUrl("https://estaticos-cdn.prensaiberica.es/clip/351fc860-3148-4c56-965d-b3a73ac12728_source-aspect-ratio_default_0.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("51").name("Zaragoza").coords(Coords.builder().latitude(41.6488).longitude(-0.8891).build()).imageUrl("https://media.traveler.es/photos/6669a6b62d7e22b44180c692/16:9/w_2560%2Cc_limit/1322345385g").autonomousCommunity("Aragón").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("52").name("Álava").coords(Coords.builder().latitude(42.8518).longitude(-2.6725).build()).imageUrl("https://www.cuadrilladeanana.es/wp-content/uploads/2024/03/que-ver-en-Alava-2.jpg").autonomousCommunity("País Vasco").build()
            );
            provinceRepository.saveAll(provinces);

            System.out.println("Provinces loaded successfully");
        };
    }
}
