package com.viu.patronAPP.config;

import com.viu.patronAPP.domain.model.Coords;
import com.viu.patronAPP.domain.model.Rol;
import com.viu.patronAPP.infrastructure.out.persistence.entity.mongo.*;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.event.EventMongoRepository;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.festivity.FestivityMongoRepository;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.province.ProvinceMongoRepository;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.user.UserMongoRepository;
import com.viu.patronAPP.infrastructure.out.persistence.repository.mongo.village.VillageMongoRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

@Configuration
@Slf4j
public class VillageLoader {

    @Bean
    public CommandLineRunner loadVillages(UserMongoRepository userMongoRepository, EventMongoRepository eventRepository, ProvinceMongoRepository provinceRepository, VillageMongoRepository villageRepository, FestivityMongoRepository festivityRepository) {
        return args -> {
            villageRepository.deleteAll();
            festivityRepository.deleteAll();
            eventRepository.deleteAll();
            provinceRepository.deleteAll();
            userMongoRepository.deleteAll();

            UserEntity admin = UserEntity.builder()
                    .name("admin")
                    .surname("admin")
                    .email("admin@admin.com")
                    .password("$2a$10$S4ZiU6Tjzax17bYc0ejCF.gtbo2qRp7Pw21eoPcbRWwletc6QbuZC")
                    .age(40)
                    .gender("M")
                    .rol(Rol.ADMIN)
                    .imageUrl("https://store-images.s-microsoft.com/image/apps.31920.f265099d-4c71-493f-b32c-b66015371675.41795bd4-3595-4260-808a-d3feb5d18d45.5b70495e-924a-49e6-a2cd-85d3bdfa781d.png")
                    .villageId("1")
                    .eventsParticipating(Arrays.asList("1", "2"))
                    .build();

            UserEntity user1 = UserEntity.builder()
                    .id("1")
                    .name("Carlos")
                    .surname("García")
                    .imageUrl("https://st3.depositphotos.com/12985790/15794/i/450/depositphotos_157947226-stock-photo-man-looking-at-camera.jpg")
                    .password("$2a$10$vhUahOWCAasqZCp/WsfeEeXWPzQYiIe5GUb4U6uUGg0.CCnGm2ea2")
                    .email("alcaldecastronuno@cm.com")
                    .villageId("1")
                    .age(29)
                    .gender("M")
                    .rol(Rol.CM)
                    .build();

            UserEntity user2 = UserEntity.builder()
                    .name("María")
                    .surname("López")
                    .imageUrl("https://vivolabs.es/wp-content/uploads/2022/03/perfil-mujer-vivo.png")
                    .password("$2a$12$do4Ri9bBOO7l4VgV62z7ruwXJl97NBjw01glJd0KwJzAyKmvHHajK")
                    .email("maria.lopez@ejemplo.com")
                    .age(32)
                    .gender("F")
                    .rol(Rol.USER)
                    .eventsParticipating(Arrays.asList("Evento2"))
                    .build();

            UserEntity user3 = UserEntity.builder()
                    .name("Lucía")
                    .imageUrl("https://vivolabs.es/wp-content/uploads/2022/03/perfil-mujer-vivo.png")

                    .surname("Martínez")
                    .password("$2a$12$gsXsDs6Rz5mE75FjA4NKMz5yblfqqpp2sF1BHYhFl6gA1yn5shczS")
                    .email("lucia.martinez@ejemplo.com")
                    .age(25)
                    .gender("F")
                    .rol(Rol.USER)
                    .eventsParticipating(Arrays.asList("1"))
                    .build();

            UserEntity user4 = UserEntity.builder()
                    .name("Javier")
                    .surname("Fernández")
                    .password("$2a$12$8gFOy0gy5GxwJqACJz9OguobebtZfi6nb/ugYYCHETv8qaERgEXWm")
                    .email("javier.fernandez@ejemplo.com")
                    .imageUrl("https://us.123rf.com/450wm/vadymvdrobot/vadymvdrobot1803/vadymvdrobot180303722/97983403-foto-de-la-situaci%C3%B3n-alegre-del-hombre-joven-aislada-sobre-la-pared-blanca-del-fondo-mirando-la.jpg?ver=6")
                    .age(35)
                    .gender("M")
                    .rol(Rol.USER)
                    .eventsParticipating(Arrays.asList("1", "1"))
                    .build();
            IntStream.range(1, 109).mapToObj(i -> UserEntity.builder().name("CM-" + i).surname("CM-" + i).email("cm" + i + "@ejemplo.com").password("$2a$12$" + "password" + i).age(30 + (i % 10)).gender(i % 2 == 0 ? "M" : "F").rol(Rol.CM).villageId("1").build()).collect(Collectors.toList()).forEach(user -> userMongoRepository.save(user));
            List<UserEntity> list = List.of(
                    UserEntity.builder().name("Juan").surname("Pérez").email("juan.perez@example.com").password("$2a$10$H5jKkP7wFfgoy6tHiLF5guc8IbGhxhtlSY3wJFNJz/jTh7kQ1lLO2").age(28).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/1.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Ana").surname("Gómez").email("ana.gomez@example.com").password("$2a$10$DlTH5LfgX9E.4zj0JY9kBd7GlTghbrSPFJ6fV6TXimBOa3MyvH/Cn").age(34).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/1.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Luis").surname("Ramírez").email("luis.ramirez@example.com").password("$2a$10$XzZ/jEDy3z1LxOIm2ptEd8XfXrRI27zNdpbflpx5iwR9.gHBklwi6").age(24).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/2.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("María").surname("Martín").email("maria.martin@example.com").password("$2a$10$1CjeX3mD5QJcWZnEj7Fozxq1aqxg8h.x6LcoZD8zwm4YkUhmwRsRi").age(30).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/2.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Pedro").surname("Sánchez").email("pedro.sanchez@example.com").password("$2a$10$Afcz31kLzj8QZK.IuCw7KXb8ZchmeV7kdJoRU1b4Y6ck4bncbVZtJ").age(40).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/3.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Laura").surname("Hernández").email("laura.hernandez@example.com").password("$2a$10$ZaZHYWG1wbYvYNn4nlEk8MzjiDBVqVtHHeGH3dVGZyxlz4gEq9pqz").age(27).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/3.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("José").surname("Lopez").email("jose.lopez@example.com").password("$2a$10$PSmsZd0YpZoI3dkf67V2X5LwMc1B9RkW4fVR52rM2hHlUl9h7fz1f").age(33).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/4.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Sofia").surname("González").email("sofia.gonzalez@example.com").password("$2a$10$54XT4Xw7BhzjcC9FqWVTLzL76lFz3dY5qXrIsKbIN.jnIVWwL9tQC").age(22).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/4.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Carlos").surname("Fernández").email("carlos.fernandez@example.com").password("$2a$10$7X1Bd.owHKHY6J8uhhv6yZOCXaNQUj2jgy0P5KX9RVhOXz2zFzSzS").age(37).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/5.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Isabel").surname("Pérez").email("isabel.perez@example.com").password("$2a$10$9pL2jwVSdYeDUhItXyfr2wweaDrr8wGf0FYcxLfj3EGkrBjjiv81m").age(31).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/5.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("David").surname("Ruiz").email("david.ruiz@example.com").password("$2a$10$Lo30Lg8xKYUfaAqXjD2ZloUov1KD5FdNKOF2Lg/OUtE3GGhprHXGe").age(26).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/6.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Elena").surname("Díaz").email("elena.diaz@example.com").password("$2a$10$L1Uxd9qzmtkgBdJgfbkYs87fgwB1ANh5tjsLvAq9YVt1BvmwhIbS6").age(29).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/6.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Miguel").surname("Jiménez").email("miguel.jimenez@example.com").password("$2a$10$TKwnXQbpzqD3qde7xTRg7OCbmxiGCgZ1fC1WVmLPCtQOQW9R8FtiY").age(32).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/7.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Raquel").surname("Vázquez").email("raquel.vazquez@example.com").password("$2a$10$Dl1q1heT0bqE4gr2cmJ79X3rrrzoqV8gobcQZtXphBOglEZiAhtYw").age(34).gender("F").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/women/7.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build(),
                    UserEntity.builder().name("Antonio").surname("Mora").email("antonio.mora@example.com").password("$2a$10$MfQUO3JlD3Q6p94SykxCZ9HvPslJhtJmH0zrd9V4FP0zOHcezkSKC").age(40).gender("M").rol(Rol.USER).imageUrl("https://randomuser.me/api/portraits/men/8.jpg").villageId("1").eventsParticipating(Arrays.asList("1")).build()
            );
            List<UserEntity> users = Arrays.asList(admin, user1, user2, user3, user4);
            userMongoRepository.saveAll(users);
            userMongoRepository.saveAll(list);
            log.info("Users loaded successfully");
            List<ProvinceEntity> provincesI = Arrays.asList(
                    ProvinceEntity.builder().id("1").name("A Coruña").coords(Coords.builder().latitude(43.3623).longitude(-8.4115).build()).imageUrl("https://viajes.chavetas.es/wp-content/uploads/2019/12/destacadaqueveracoruna-850x453.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("2").name("Albacete").coords(Coords.builder().latitude(38.9943).longitude(-1.8564).build()).imageUrl("https://sabersabor.es/wp-content/uploads/2021/07/Visita-guiada-a-Albacete.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("3").name("Alicante").coords(Coords.builder().latitude(38.3452).longitude(-0.4810).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-alicante.jpg").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("4").name("Almería").coords(Coords.builder().latitude(36.8340).longitude(-2.4637).build()).imageUrl("https://www.servigroup.com/assets/cache/uploads/gallery/proposals/excursiones/que-ver-almeria/1280x720/alcazaba-almeria-1701094733.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("5").name("Ávila").coords(Coords.builder().latitude(40.6566).longitude(-4.6818).build()).imageUrl("https://www.hola.com/horizon/landscape/ca3e997be14f-avila-murallas-panoramica-t.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("6").name("Badajoz").coords(Coords.builder().latitude(38.8794).longitude(-6.9706).build()).imageUrl("https://media.traveler.es/photos/61377022d7c7024f9175ecea/16:9/w_2000,h_1125,c_limit/131678.jpg").autonomousCommunity("Extremadura").build(),
                    ProvinceEntity.builder().id("7").name("Barcelona").coords(Coords.builder().latitude(41.3851).longitude(2.1734).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-barcelona-1.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("8").name("Vizcaya").coords(Coords.builder().latitude(43.2630).longitude(-2.9349).build()).imageUrl("https://media.traveler.es/photos/64f59cd0756c466be81874ab/16:9/w_2560%2Cc_limit/david-vives--AQJPGnTVLE-unsplash.jpg").autonomousCommunity("País Vasco").build(),
                    ProvinceEntity.builder().id("9").name("Burgos").coords(Coords.builder().latitude(42.3439).longitude(-3.6969).build()).imageUrl("https://www.espanafascinante.com/asset/thumbnail,1280,720,center,center/media/espanafascinante/images/2018/07/09/20180709103536242329.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("10").name("Cáceres").coords(Coords.builder().latitude(39.4752).longitude(-6.3722).build()).imageUrl("https://media.timeout.com/images/106012284/750/422/image.jpg").autonomousCommunity("Extremadura").build(),
                    ProvinceEntity.builder().id("11").name("Cádiz").coords(Coords.builder().latitude(36.5271).longitude(-6.2886).build()).imageUrl("https://www.cadizturismo.com/storage/app/media/uploaded-files/p-cadiz_turismo.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("12").name("Castellón").coords(Coords.builder().latitude(39.9864).longitude(-0.0513).build()).imageUrl("https://www.ccsalera.com/wp-content/uploads/2022/11/monumentos-castellon-scaled.jpg").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("13").name("Ceuta").coords(Coords.builder().latitude(35.8893).longitude(-5.3167).build()).imageUrl("https://revistacentinela.es/wp-content/uploads/2018/11/Ceuta-panoramica.jpg").autonomousCommunity("Ceuta").build(),
                    ProvinceEntity.builder().id("14").name("Ciudad Real").coords(Coords.builder().latitude(38.9861).longitude(-3.9275).build()).imageUrl("https://abrasador.com/wp-content/uploads/2021/12/Plaza_Mayor_de_Ciudad_Reak-min-scaled.jpeg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("15").name("Córdoba").coords(Coords.builder().latitude(37.8882).longitude(-4.7794).build()).imageUrl("https://multimedia.andalucia.org/media/C1DF41C3E6EF456A8B4A9B4845C32593/img/7B2A371526454055A71AC38C335E1834/16-20_Puente_Romano_y_Mezquita_de_Cordoba_Cordoba.jpg?responsive").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("16").name("Cuenca").coords(Coords.builder().latitude(40.0704).longitude(-2.1374).build()).imageUrl("https://repositorio.turismocastillalamancha.com/miscelanea/178474/36/2cbf/cuenca.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("17").name("Girona").coords(Coords.builder().latitude(41.9794).longitude(2.8214).build()).imageUrl("https://mesto-barcelona.cz/data/uploads/girona-opevneni.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("18").name("Granada").coords(Coords.builder().latitude(37.1773).longitude(-3.5986).build()).imageUrl("https://content.r9cdn.net/rimg/dimg/3b/c2/b4c4bfb9-city-27138-55689ae0.jpg?width=1366&height=768&xhint=1902&yhint=1090&crop=true").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("19").name("Guadalajara").coords(Coords.builder().latitude(40.6333).longitude(-3.1636).build()).imageUrl("https://fotos.hoteles.net/articulos/guia-huelva-ciudad-6159-1.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("20").name("Huelva").coords(Coords.builder().latitude(37.2595).longitude(-6.9485).build()).imageUrl("https://media.traveler.es/photos/61376d9070e3cff8b85f8c02/16:9/w_1280,c_limit/139897.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("21").name("Huesca").coords(Coords.builder().latitude(42.1407).longitude(-0.4085).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/huesca-capital.jpg").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("22").name("Jaén").coords(Coords.builder().latitude(37.7647).longitude(-3.7904).build()).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/contenidos-imagenes/viajar/nos-gusta/curiosidades-de-la-catedral-de-la-asuncion-de-jaen/gr-cms-media-featured_images-none-a40e0813-f000-4767-80ca-ccf0d9fc83fb-catedral-jaen-002.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("23").name("Las Palmas").coords(Coords.builder().latitude(28.0994).longitude(-15.4134).build()).imageUrl("https://static-resources.mirai.com/wp-content/uploads/sites/1738/20231117091703/Vistas-Las-Palmas-de-GC.jpg").autonomousCommunity("Canarias").build(),
                    ProvinceEntity.builder().id("24").name("León").coords(Coords.builder().latitude(42.5977).longitude(-5.5671).build()).imageUrl("https://www.spain.info/.content/imagenes/cabeceras-grandes/castilla-leon/leon-plaza-mayor-118901284.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("25").name("Lleida").coords(Coords.builder().latitude(41.6161).longitude(0.6206).build()).imageUrl("https://espanaxdescubrir.com/wp-content/uploads/2021/12/Lleida-2.jpg").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("26").name("La Rioja").coords(Coords.builder().latitude(42.4661).longitude(-2.4457).build()).imageUrl("https://s2.ppllstatics.com/larioja/www/multimedia/202201/08/media/cortadas/mercado-principal-kijH-U160483022264mvF-1968x1330@La%20Rioja.jpg").autonomousCommunity("La Rioja").build(),
                    ProvinceEntity.builder().id("27").name("Lugo").coords(Coords.builder().latitude(43.0032).longitude(-7.5582).build()).imageUrl("https://www.spain.info/export/sites/segtur/.content/imagenes/cabeceras-grandes/galicia/lugo-murallas-catedral-s490049140.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("28").name("Madrid").coords(Coords.builder().latitude(40.4168).longitude(-3.7038).build()).imageUrl("https://img.static-kl.com/images/media/65848EF5-2848-4EA7-BE113130180A0A55").autonomousCommunity("Madrid").build(),
                    ProvinceEntity.builder().id("29").name("Málaga").coords(Coords.builder().latitude(36.7203).longitude(-4.4199).build()).imageUrl("https://coeohouse.com/wp-content/uploads/2023/03/17-facts-about-Malaga.jpeg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("30").name("Melilla").coords(Coords.builder().latitude(35.2920).longitude(-2.9381).build()).imageUrl("https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/44/b9/a0/vista-aerea-de-la-ciudad.jpg?w=900&h=500&s=1").autonomousCommunity("Melilla").build(),
                    ProvinceEntity.builder().id("31").name("Murcia").coords(Coords.builder().latitude(37.9844).longitude(-1.1285).build()).imageUrl("https://www.espanaguide.com/images/murcia/calle-traperia-murcia-mobile.jpg").autonomousCommunity("Murcia").build(),
                    ProvinceEntity.builder().id("32").name("Ourense").coords(Coords.builder().latitude(42.3365).longitude(-7.8637).build()).imageUrl("https://www.spain.info/.content/imagenes/cabeceras-grandes/galicia/ourense-galicia-plaza-mayor-177596441-c-rodrigo-garrido-shutterstock.jpg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("33").name("Asturias").coords(Coords.builder().latitude(43.3623).longitude(-5.8494).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/que-visitar-en-asturias.jpg").autonomousCommunity("Asturias").build(),
                    ProvinceEntity.builder().id("34").name("Palencia").coords(Coords.builder().latitude(42.0078).longitude(-4.5346).build()).imageUrl("https://www.lavanguardia.com/files/og_thumbnail/uploads/2017/06/14/5fa3c84a0b3cd.jpeg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("35").name("Illes Balears").coords(Coords.builder().latitude(39.5711).longitude(2.6518).build()).imageUrl("https://estaticos-cdn.prensaiberica.es/clip/49784cc4-e033-4960-ac35-70b5c2d94565_original-libre-aspect-ratio_default_0.jpg").autonomousCommunity("Illes Balears").build(),
                    ProvinceEntity.builder().id("36").name("Navarra").coords(Coords.builder().latitude(42.8141).longitude(-1.6452).build()).imageUrl("https://turismo.navarra.com/wp-content/uploads/Castillo_Olite_Navarra1.jpg").autonomousCommunity("Navarra").build(),
                    ProvinceEntity.builder().id("37").name("Pontevedra").coords(Coords.builder().latitude(42.4338).longitude(-8.6480).build()).imageUrl("https://www.guiategalicia.com/wp-content/uploads/2017/08/IMG_4716.jpeg").autonomousCommunity("Galicia").build(),
                    ProvinceEntity.builder().id("38").name("Salamanca").coords(Coords.builder().latitude(40.9674).longitude(-5.6654).build()).imageUrl("https://salamanca.es/images/promo_salamanca_40seg.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("39").name("Guipúzcoa").coords(Coords.builder().latitude(43.3172).longitude(-1.9819).build()).imageUrl("https://www.barcelo.com/guia-turismo/wp-content/uploads/2024/09/ok-turismo-gipuzkoa.jpg").autonomousCommunity("País Vasco").build(),
                    ProvinceEntity.builder().id("40").name("Santa Cruz De Tenerife").coords(Coords.builder().latitude(28.4629).longitude(-16.2472).build()).imageUrl("https://www.spain.info/export/sites/segtur/.content/imagenes/cabeceras-grandes/canarias/santa-cruz-de-tenerife-s362881445.jpg").autonomousCommunity("Canarias").build(),
                    ProvinceEntity.builder().id("41").name("Cantabria").coords(Coords.builder().latitude(43.1828).longitude(-3.9878).build()).imageUrl("https://lacorujadelebro.com/wp-content/uploads/Cantabria-2-2.jpg").autonomousCommunity("Cantabria").build(),
                    ProvinceEntity.builder().id("42").name("Segovia").coords(Coords.builder().latitude(40.9481).longitude(-4.1187).build()).imageUrl("https://www.turismocastillayleon.com/es/patrimonio-cultura/puentes/acueducto-segovia.ficheros/193170-Acueducto%20de%20Segovia.jpg/g,193170-Acueducto%20de%20Segovia.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("43").name("Sevilla").coords(Coords.builder().latitude(37.3886).longitude(-5.9823).build()).imageUrl("https://img2.rtve.es/v/6864365?w=1600&preview=1681890137650.jpg").autonomousCommunity("Andalucía").build(),
                    ProvinceEntity.builder().id("44").name("Soria").coords(Coords.builder().latitude(41.7644).longitude(-2.4633).build()).imageUrl("https://fotografias.lasexta.com/clipping/cmsimages02/2023/03/21/2EAEFC1A-5C54-4ECE-BA02-50AE25063E1C/vista-aerea-soria_default.jpgg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("45").name("Tarragona").coords(Coords.builder().latitude(41.1187).longitude(1.2445).build()).imageUrl("https://content.r9cdn.net/rimg/dimg/8a/55/f710b8f3-city-40385-1717ca7b5af.jpg?width=1200&height=630&xhint=2289&yhint=2332&crop=true").autonomousCommunity("Cataluña").build(),
                    ProvinceEntity.builder().id("46").name("Teruel").coords(Coords.builder().latitude(40.3430).longitude(-1.1062).build()).imageUrl("https://viajes.nationalgeographic.com.es/medio/2018/02/27/teruel__1280x720.jpg").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("47").name("Toledo").coords(Coords.builder().latitude(39.8628).longitude(-4.0273).build()).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/contenidos-imagenes/viajar/vamos-de-excursion/que-ver-toledo/gr-cms-media-featured_images-none-1c489cc1-bf59-4b9d-acec-875c41f2c4fb-01-puente-de-alcantara-vista-general.jpg").autonomousCommunity("Castilla-La Mancha").build(),
                    ProvinceEntity.builder().id("48").name("Valencia").coords(Coords.builder().latitude(39.4699).longitude(-0.3763).build()).imageUrl("https://img.nh-hotels.net/8yYbq/aGoV8/original/Valencia_CAC.jpg?output-quality=70&resize=*:*&background-color=white").autonomousCommunity("Comunidad Valenciana").build(),
                    ProvinceEntity.builder().id("49").name("Valladolid").coords(Coords.builder().latitude(41.6523).longitude(-4.7282).build()).imageUrl("https://www.cideu.org/wp-content/uploads/2019/12/valladolid-2.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("50").name("Zamora").coords(Coords.builder().latitude(41.5035).longitude(-5.7448).build()).imageUrl("https://estaticos-cdn.prensaiberica.es/clip/351fc860-3148-4c56-965d-b3a73ac12728_source-aspect-ratio_default_0.jpg").autonomousCommunity("Castilla y León").build(),
                    ProvinceEntity.builder().id("51").name("Zaragoza").coords(Coords.builder().latitude(41.6488).longitude(-0.8891).build()).imageUrl("https://media.traveler.es/photos/6669a6b62d7e22b44180c692/16:9/w_2560%2Cc_limit/1322345385g").autonomousCommunity("Aragón").autonomousCommunity("Aragón").build(),
                    ProvinceEntity.builder().id("52").name("Álava").coords(Coords.builder().latitude(42.8518).longitude(-2.6725).build()).imageUrl("https://www.cuadrilladeanana.es/wp-content/uploads/2024/03/que-ver-en-Alava-2.jpg").autonomousCommunity("País Vasco").build()
            );
            provinceRepository.saveAll(provincesI);

            log.info("Provinces loaded successfully");
            List<ProvinceEntity> provinces = provinceRepository.findAll();
            ProvinceEntity valladolid = provinces.stream().filter(province -> province.getId().equals("49")).findFirst().orElse(null);
            ProvinceEntity leon = provinces.stream().filter(province -> province.getId().equals("24")).findFirst().orElse(null);
            ProvinceEntity burgos = provinces.stream().filter(province -> province.getId().equals("9")).findFirst().orElse(null);


            eventRepository.deleteAll();
            List<UserEntity> adminUsers = userMongoRepository.findByEmail("admin@admin.com").stream().toList();
            UserEntity adminUser = adminUsers.get(0);

            List<EventEntity> events7 = List.of(
                    EventEntity.builder().id("1").attendees(List.of(adminUser)).name("Concierto de Folk").description("Espectáculo musical al aire libre con artistas locales.").startDate(LocalDateTime.of(2025, 9, 19, 16, 0)).endDate(LocalDateTime.of(2025, 9, 19, 18, 0)).coords(List.of(Coords.builder().latitude(41.389710).longitude(-5.263901).build())).maxCapacity(150).attendees(List.of(adminUser)).build(),
                    EventEntity.builder().id("2").attendees(List.of(adminUser)).name("Exposición de Artesanía").description("Muestra de productos locales hechos a mano.").startDate(LocalDateTime.of(2025, 9, 20, 10, 0)).endDate(LocalDateTime.of(2025, 9, 20, 13, 0)).coords(List.of(Coords.builder().latitude(41.389802).longitude(-5.263589).build())).maxCapacity(50).attendees(List.of(adminUser)).build(),
                    EventEntity.builder().id("3").name("Degustación de Vinos").description("Evento gastronómico con cata de vinos de la región.").startDate(LocalDateTime.of(2025, 9, 20, 17, 0)).endDate(LocalDateTime.of(2025, 9, 20, 19, 0)).coords(List.of(Coords.builder().latitude(41.388940).longitude(-5.263813).build())).maxCapacity(75).attendees(List.of()).build(),
                    EventEntity.builder().id("4").name("Carrera Popular").description("Competición para corredores de todas las edades.").startDate(LocalDateTime.of(2025, 9, 21, 9, 0)).endDate(LocalDateTime.of(2025, 9, 21, 11, 0)).coords(List.of(Coords.builder().latitude(41.388701).longitude(-5.263379).build())).maxCapacity(200).attendees(List.of()).build(),
                    EventEntity.builder().id("5").name("Teatro al Aire Libre").description("Representación de una obra clásica en la plaza del pueblo.").startDate(LocalDateTime.of(2025, 9, 21, 18, 0)).endDate(LocalDateTime.of(2025, 9, 21, 20, 0)).coords(List.of(Coords.builder().latitude(41.388730).longitude(-5.262751).build())).maxCapacity(100).attendees(List.of()).build(),
                    EventEntity.builder().id("6").name("Concurso de Fotografía").description("Exposición y premiación de las mejores fotos locales.").startDate(LocalDateTime.of(2025, 9, 19, 16, 0)).endDate(LocalDateTime.of(2025, 9, 19, 18, 0)).coords(List.of(Coords.builder().latitude(41.388619).longitude(-5.262314).build())).maxCapacity(50).attendees(List.of()).build(),
                    EventEntity.builder().id("7").name("Taller de Cocina Tradicional").description("Aprende a preparar platos típicos de la región.").startDate(LocalDateTime.of(2025, 9, 20, 11, 0)).endDate(LocalDateTime.of(2025, 9, 20, 13, 30)).coords(List.of(Coords.builder().latitude(41.388635).longitude(-5.261608).build())).maxCapacity(30).attendees(List.of()).build(),
                    EventEntity.builder().id("8").name("Paseo Guiado por la Reserva Natural").description("Ruta a pie para conocer la flora y fauna de Castronuño.").startDate(LocalDateTime.of(2025, 9, 22, 9, 0)).endDate(LocalDateTime.of(2025, 9, 22, 11, 30)).coords(List.of(Coords.builder().latitude(41.389232).longitude(-5.210620).build())).maxCapacity(25).attendees(List.of()).build(),
                    EventEntity.builder().id("9").name("Cine Bajo las Estrellas").description("Proyección de una película en un espacio abierto.").startDate(LocalDateTime.of(2025, 9, 21, 21, 30)).endDate(LocalDateTime.of(2025, 9, 21, 23, 30)).coords(List.of(Coords.builder().latitude(41.388665).longitude(-5.260867).build())).maxCapacity(120).attendees(List.of()).build(),
                    EventEntity.builder().id("10").name("Feria Gastronómica").description("Un recorrido por los sabores típicos de Castronuño.").startDate(LocalDateTime.of(2025, 9, 22, 13, 0)).endDate(LocalDateTime.of(2025, 9, 22, 15, 0)).coords(List.of(Coords.builder().latitude(41.390141).longitude(-5.261502).build())).maxCapacity(100).attendees(List.of()).build(),
                    EventEntity.builder().id("11").name("Corrida toros").description("La increible y tradicional corrida de toros de Castronuño.").startDate(LocalDateTime.of(2025, 9, 22, 13, 0)).endDate(LocalDateTime.of(2025, 9, 22, 15, 0)).coords(List.of(
                            Coords.builder().latitude(41.390354).longitude(-5.256962).build(),
                            Coords.builder().latitude(41.390101).longitude(-5.258039).build(),
                            Coords.builder().latitude(41.389560).longitude(-5.259122).build(),
                            Coords.builder().latitude(41.389232).longitude(-5.260680).build()
                    )).maxCapacity(100).attendees(List.of()).build()

            );

            eventRepository.saveAll(events7);
            log.info("Events loaded successfully");

            List<FestivityEntity> festivities = Arrays.asList(
                    FestivityEntity.builder().name("Fiesta Patronal San Pedro").id("1").events(new ArrayList<>()).patron("San Pedro").startDate(LocalDate.of(2025, 4, 1)).endDate(LocalDate.of(2025, 4, 2)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa María").id("2").events(new ArrayList<>()).patron("Santa María").startDate(LocalDate.of(2025, 6, 15)).endDate(LocalDate.of(2025, 6, 17)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Juan").id("3").events(new ArrayList<>()).patron("San Juan").startDate(LocalDate.of(2025, 8, 23)).endDate(LocalDate.of(2025, 8, 24)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("4").events(new ArrayList<>()).patron("San Miguel").startDate(LocalDate.of(2025, 9, 29)).endDate(LocalDate.of(2025, 9, 30)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("5").events(new ArrayList<>()).patron("San Antonio").startDate(LocalDate.of(2025, 10, 13)).endDate(LocalDate.of(2025, 10, 14)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Virgen del Carmen").id("6").events(new ArrayList<>()).patron("Virgen del Carmen").startDate(LocalDate.of(2025, 7, 16)).endDate(LocalDate.of(2025, 7, 17)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San José").id("7").events(events7).patron("San José").startDate(LocalDate.of(2025, 9, 19)).endDate(LocalDate.of(2025, 9, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Francisco").id("8").events(new ArrayList<>()).patron("San Francisco").startDate(LocalDate.of(2025, 10, 4)).endDate(LocalDate.of(2025, 10, 5)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Teresa").id("9").events(new ArrayList<>()).patron("Santa Teresa").startDate(LocalDate.of(2025, 10, 15)).endDate(LocalDate.of(2025, 10, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora de la Asunción").id("10").events(new ArrayList<>()).patron("Nuestra Señora de la Asunción").startDate(LocalDate.of(2025, 8, 15)).endDate(LocalDate.of(2025, 8, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Isidro").id("11").events(new ArrayList<>()).patron("San Isidro").startDate(LocalDate.of(2025, 5, 15)).endDate(LocalDate.of(2025, 5, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("12").events(new ArrayList<>()).patron("Santiago Apóstol").startDate(LocalDate.of(2025, 7, 25)).endDate(LocalDate.of(2025, 7, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Bartolomé").id("13").events(new ArrayList<>()).patron("San Bartolomé").startDate(LocalDate.of(2025, 8, 24)).endDate(LocalDate.of(2025, 8, 25)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Roque").id("14").events(new ArrayList<>()).patron("San Roque").startDate(LocalDate.of(2025, 8, 16)).endDate(LocalDate.of(2025, 8, 17)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("15").events(new ArrayList<>()).patron("Santa Ana").startDate(LocalDate.of(2025, 7, 26)).endDate(LocalDate.of(2025, 7, 27)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Nicolás").id("16").events(new ArrayList<>()).patron("San Nicolás").startDate(LocalDate.of(2025, 12, 6)).endDate(LocalDate.of(2025, 12, 7)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Rosario").id("17").events(new ArrayList<>()).patron("Nuestra Señora del Rosario").startDate(LocalDate.of(2025, 10, 7)).endDate(LocalDate.of(2025, 10, 8)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Fermín").id("18").events(new ArrayList<>()).patron("San Fermín").startDate(LocalDate.of(2025, 7, 7)).endDate(LocalDate.of(2025, 7, 8)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Vicente").id("19").events(new ArrayList<>()).patron("San Vicente").startDate(LocalDate.of(2025, 1, 22)).endDate(LocalDate.of(2025, 1, 23)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Andrés").id("20").events(new ArrayList<>()).patron("San Andrés").startDate(LocalDate.of(2025, 11, 30)).endDate(LocalDate.of(2025, 12, 1)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Bárbara").id("21").events(new ArrayList<>()).patron("Santa Bárbara").startDate(LocalDate.of(2025, 12, 4)).endDate(LocalDate.of(2025, 12, 5)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Valentín").id("22").events(new ArrayList<>()).patron("San Valentín").startDate(LocalDate.of(2025, 2, 14)).endDate(LocalDate.of(2025, 2, 15)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Blas").id("23").events(new ArrayList<>()).patron("San Blas").startDate(LocalDate.of(2025, 2, 3)).endDate(LocalDate.of(2025, 2, 4)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Jorge").id("24").events(new ArrayList<>()).patron("San Jorge").startDate(LocalDate.of(2025, 4, 23)).endDate(LocalDate.of(2025, 4, 24)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Cristóbal").id("25").events(new ArrayList<>()).patron("San Cristóbal").startDate(LocalDate.of(2025, 7, 10)).endDate(LocalDate.of(2025, 7, 11)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Sebastián").id("26").events(new ArrayList<>()).patron("San Sebastián").startDate(LocalDate.of(2025, 1, 20)).endDate(LocalDate.of(2025, 1, 21)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Virgen de Guadalupe").id("27").events(new ArrayList<>()).patron("Virgen de Guadalupe").startDate(LocalDate.of(2025, 12, 12)).endDate(LocalDate.of(2025, 12, 13)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Virgen de Fátima").id("28").events(new ArrayList<>()).patron("Virgen de Fátima").startDate(LocalDate.of(2025, 5, 13)).endDate(LocalDate.of(2025, 5, 14)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Clara").id("29").events(new ArrayList<>()).patron("Santa Clara").startDate(LocalDate.of(2025, 8, 11)).endDate(LocalDate.of(2025, 8, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Ramón").id("30").events(new ArrayList<>()).patron("San Ramón").startDate(LocalDate.of(2025, 8, 31)).endDate(LocalDate.of(2025, 9, 1)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Agustín").id("31").events(new ArrayList<>()).patron("San Agustín").startDate(LocalDate.of(2025, 8, 28)).endDate(LocalDate.of(2025, 8, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Gregorio").id("32").events(new ArrayList<>()).patron("San Gregorio").startDate(LocalDate.of(2025, 5, 9)).endDate(LocalDate.of(2025, 5, 10)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Mateo").id("33").events(new ArrayList<>()).patron("San Mateo").startDate(LocalDate.of(2025, 9, 21)).endDate(LocalDate.of(2025, 9, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Lucía").id("34").events(new ArrayList<>()).patron("Santa Lucía").startDate(LocalDate.of(2025, 12, 13)).endDate(LocalDate.of(2025, 12, 14)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Pablo").id("35").events(new ArrayList<>()).patron("San Pablo").startDate(LocalDate.of(2025, 6, 29)).endDate(LocalDate.of(2025, 6, 30)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Rafael").id("36").events(new ArrayList<>()).patron("San Rafael").startDate(LocalDate.of(2025, 10, 24)).endDate(LocalDate.of(2025, 10, 25)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Joaquín").id("37").events(new ArrayList<>()).patron("San Joaquín").startDate(LocalDate.of(2025, 7, 26)).endDate(LocalDate.of(2025, 7, 27)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Catalina").id("38").events(new ArrayList<>()).patron("Santa Catalina").startDate(LocalDate.of(2025, 11, 25)).endDate(LocalDate.of(2025, 11, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Cruz").id("39").events(new ArrayList<>()).patron("Santa Cruz").startDate(LocalDate.of(2025, 5, 3)).endDate(LocalDate.of(2025, 5, 4)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Marcos").id("40").events(new ArrayList<>()).patron("San Marcos").startDate(LocalDate.of(2025, 4, 25)).endDate(LocalDate.of(2025, 4, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Esteban").id("41").events(new ArrayList<>()).patron("San Esteban").startDate(LocalDate.of(2025, 12, 26)).endDate(LocalDate.of(2025, 12, 27)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Virgen de los Dolores").id("42").events(new ArrayList<>()).patron("Virgen de los Dolores").startDate(LocalDate.of(2025, 9, 15)).endDate(LocalDate.of(2025, 9, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Lorenzo").id("43").events(new ArrayList<>()).patron("San Lorenzo").startDate(LocalDate.of(2025, 8, 10)).endDate(LocalDate.of(2025, 8, 11)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Felipe").id("44").events(new ArrayList<>()).patron("San Felipe").startDate(LocalDate.of(2025, 5, 3)).endDate(LocalDate.of(2025, 5, 4)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Judas Tadeo").id("45").events(new ArrayList<>()).patron("San Judas Tadeo").startDate(LocalDate.of(2025, 10, 28)).endDate(LocalDate.of(2025, 10, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Marcos").id("46").events(new ArrayList<>()).patron("San Marcos").startDate(LocalDate.of(2025, 4, 25)).endDate(LocalDate.of(2025, 4, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Juan de la Cruz").id("47").events(new ArrayList<>()).patron("San Juan de la Cruz").startDate(LocalDate.of(2025, 12, 14)).endDate(LocalDate.of(2025, 12, 15)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Martín").id("48").events(new ArrayList<>()).patron("San Martín").startDate(LocalDate.of(2025, 11, 11)).endDate(LocalDate.of(2025, 11, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Valentín").id("49").events(new ArrayList<>()).patron("San Valentín").startDate(LocalDate.of(2025, 2, 14)).endDate(LocalDate.of(2025, 2, 15)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Virgen de la Merced").id("50").events(new ArrayList<>()).patron("Virgen de la Merced").startDate(LocalDate.of(2025, 9, 24)).endDate(LocalDate.of(2025, 9, 25)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Roque").id("151").events(new ArrayList<>()).patron("Roque").startDate(LocalDate.of(2025, 10, 18)).endDate(LocalDate.of(2025, 10, 19)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Roque").id("152").events(new ArrayList<>()).patron("Roque").startDate(LocalDate.of(2025, 10, 9)).endDate(LocalDate.of(2025, 10, 10)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("153").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 5, 19)).endDate(LocalDate.of(2025, 5, 20)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("154").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 9, 28)).endDate(LocalDate.of(2025, 9, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("155").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 11, 17)).endDate(LocalDate.of(2025, 11, 18)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa María").id("156").events(new ArrayList<>()).patron("María").startDate(LocalDate.of(2025, 3, 11)).endDate(LocalDate.of(2025, 3, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("157").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 2, 25)).endDate(LocalDate.of(2025, 2, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa María").id("158").events(new ArrayList<>()).patron("María").startDate(LocalDate.of(2025, 7, 18)).endDate(LocalDate.of(2025, 7, 19)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("159").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 4, 7)).endDate(LocalDate.of(2025, 4, 8)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("160").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 5, 23)).endDate(LocalDate.of(2025, 5, 24)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("161").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 2, 17)).endDate(LocalDate.of(2025, 2, 18)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("162").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 4, 17)).endDate(LocalDate.of(2025, 4, 18)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Isidro").id("163").events(new ArrayList<>()).patron("Isidro").startDate(LocalDate.of(2025, 1, 28)).endDate(LocalDate.of(2025, 1, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Teresa").id("164").events(new ArrayList<>()).patron("Teresa").startDate(LocalDate.of(2025, 8, 4)).endDate(LocalDate.of(2025, 8, 5)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("165").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 8, 11)).endDate(LocalDate.of(2025, 8, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("166").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 8, 19)).endDate(LocalDate.of(2025, 8, 20)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("167").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 6, 18)).endDate(LocalDate.of(2025, 6, 19)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("168").events(new ArrayList<>()).patron("Ana").startDate(LocalDate.of(2025, 5, 25)).endDate(LocalDate.of(2025, 5, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("169").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 7, 12)).endDate(LocalDate.of(2025, 7, 13)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("170").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 1, 11)).endDate(LocalDate.of(2025, 1, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("171").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 4, 21)).endDate(LocalDate.of(2025, 4, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Francisco").id("172").events(new ArrayList<>()).patron("Francisco").startDate(LocalDate.of(2025, 11, 28)).endDate(LocalDate.of(2025, 11, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Teresa").id("173").events(new ArrayList<>()).patron("Teresa").startDate(LocalDate.of(2025, 7, 8)).endDate(LocalDate.of(2025, 7, 9)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("174").events(new ArrayList<>()).patron("Ana").startDate(LocalDate.of(2025, 8, 24)).endDate(LocalDate.of(2025, 8, 25)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("175").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 6, 23)).endDate(LocalDate.of(2025, 6, 24)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Teresa").id("176").events(new ArrayList<>()).patron("Teresa").startDate(LocalDate.of(2025, 3, 15)).endDate(LocalDate.of(2025, 3, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("177").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 11, 13)).endDate(LocalDate.of(2025, 11, 14)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Isidro").id("178").events(new ArrayList<>()).patron("Isidro").startDate(LocalDate.of(2025, 3, 19)).endDate(LocalDate.of(2025, 3, 20)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Roque").id("179").events(new ArrayList<>()).patron("Roque").startDate(LocalDate.of(2025, 7, 8)).endDate(LocalDate.of(2025, 7, 9)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("180").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 1, 21)).endDate(LocalDate.of(2025, 1, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("181").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 3, 20)).endDate(LocalDate.of(2025, 3, 21)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("182").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 3, 26)).endDate(LocalDate.of(2025, 3, 27)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Francisco").id("183").events(new ArrayList<>()).patron("Francisco").startDate(LocalDate.of(2025, 9, 28)).endDate(LocalDate.of(2025, 9, 29)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Isidro").id("184").events(new ArrayList<>()).patron("Isidro").startDate(LocalDate.of(2025, 4, 6)).endDate(LocalDate.of(2025, 4, 7)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("185").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 6, 7)).endDate(LocalDate.of(2025, 6, 8)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("186").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 3, 15)).endDate(LocalDate.of(2025, 3, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("187").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 9, 2)).endDate(LocalDate.of(2025, 9, 3)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("188").events(new ArrayList<>()).patron("Ana").startDate(LocalDate.of(2025, 9, 15)).endDate(LocalDate.of(2025, 9, 16)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Francisco").id("189").events(new ArrayList<>()).patron("Francisco").startDate(LocalDate.of(2025, 11, 3)).endDate(LocalDate.of(2025, 11, 4)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("191").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 5, 21)).endDate(LocalDate.of(2025, 5, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Teresa").id("192").events(new ArrayList<>()).patron("Teresa").startDate(LocalDate.of(2025, 4, 21)).endDate(LocalDate.of(2025, 4, 22)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa María").id("193").events(new ArrayList<>()).patron("María").startDate(LocalDate.of(2025, 12, 11)).endDate(LocalDate.of(2025, 12, 12)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("194").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 3, 22)).endDate(LocalDate.of(2025, 3, 23)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("195").events(new ArrayList<>()).patron("Ana").startDate(LocalDate.of(2025, 12, 13)).endDate(LocalDate.of(2025, 12, 14)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("196").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 4, 1)).endDate(LocalDate.of(2025, 4, 2)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa Ana").id("197").events(new ArrayList<>()).patron("Ana").startDate(LocalDate.of(2025, 11, 17)).endDate(LocalDate.of(2025, 11, 18)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("198").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 9, 26)).endDate(LocalDate.of(2025, 9, 27)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("199").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 7, 2)).endDate(LocalDate.of(2025, 7, 3)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Isidro").id("200").events(new ArrayList<>()).patron("Isidro").startDate(LocalDate.of(2025, 9, 27)).endDate(LocalDate.of(2025, 9, 28)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Francisco").id("201").events(new ArrayList<>()).patron("Francisco").startDate(LocalDate.of(2025, 6, 18)).endDate(LocalDate.of(2025, 6, 19)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("202").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 8, 3)).endDate(LocalDate.of(2025, 8, 4)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("203").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 12, 23)).endDate(LocalDate.of(2025, 12, 24)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("204").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 11, 6)).endDate(LocalDate.of(2025, 11, 7)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santiago Apóstol").id("205").events(new ArrayList<>()).patron("Apóstol").startDate(LocalDate.of(2025, 8, 2)).endDate(LocalDate.of(2025, 8, 3)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Santa María").id("206").events(new ArrayList<>()).patron("María").startDate(LocalDate.of(2025, 4, 20)).endDate(LocalDate.of(2025, 4, 21)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Miguel").id("207").events(new ArrayList<>()).patron("Miguel").startDate(LocalDate.of(2025, 7, 25)).endDate(LocalDate.of(2025, 7, 26)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal San Antonio").id("208").events(new ArrayList<>()).patron("Antonio").startDate(LocalDate.of(2025, 1, 5)).endDate(LocalDate.of(2025, 1, 6)).build(),
                    FestivityEntity.builder().name("Fiesta Patronal Nuestra Señora del Pilar").id("210").events(new ArrayList<>()).patron("Pilar").startDate(LocalDate.of(2025, 1, 2)).endDate(LocalDate.of(2025, 1, 3)).build()
            );
            festivityRepository.saveAll(festivities);
            log.info("Festivities loaded successfully");
            List<FestivityEntity> festivitiesEntities = festivityRepository.findAll();
            List<VillageEntity> villages = Arrays.asList(
                    VillageEntity.builder().name("Castronuño").id("1").coords(Coords.builder().latitude(41.390485).longitude(-5.262498).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("7")).findFirst().orElse(null)).imageUrl("https://www.cyltv.es/mediao/8AC773D2-CB16-36DA-42443158195DB759.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Villarejo de Órbigo").id("2").coords(Coords.builder().latitude(42.445197).longitude(-5.903779).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("2")).findFirst().orElse(null)).imageUrl("https://www.diocesisastorga.es/recursos/parroquias/d51460a45f36d2a8b6ba9c189e1a1e9d.jpg").province(leon).build(),
                    VillageEntity.builder().name("Villaornate y Castro").id("3").coords(Coords.builder().latitude(42.184812).longitude(-5.549757).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("3")).findFirst().orElse(null)).imageUrl("https://leonsurdigital.com/upload/images/06_2023/9234_8621_img_28474-1.jpg").province(leon).build(),
                    VillageEntity.builder().name("Villaobispo De Otero").id("4").coords(Coords.builder().latitude(42.499988).longitude(-6.058563).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("4")).findFirst().orElse(null)).imageUrl("https://media2.clubrural.com/img990x400/pueblos/leon/villaobispo-de-otero/20160219064630-leon-villaobispo-de-otero.jpg").province(leon).build(),
                    VillageEntity.builder().name("Palanquinos").id("5").coords(Coords.builder().latitude(42.471355).longitude(-5.480471).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("5")).findFirst().orElse(null)).imageUrl("https://leonsurdigital.com/upload/images/04_2024/1263_4-palanquinos.jpg").province(leon).build(),
                    VillageEntity.builder().name("Atapuerca").id("6").coords(Coords.builder().latitude(42.338611).longitude(-3.647222).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("6")).findFirst().orElse(null)).imageUrl("https://example.com/atapuerca.jpg").province(burgos).build(),
                    VillageEntity.builder().name("Alba de Tormes").id("7").coords(Coords.builder().latitude(40.948056).longitude(-5.463611).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("1")).findFirst().orElse(null)).imageUrl("https://example.com/alba_de_tormes.jpg").province(burgos).build(),
                    VillageEntity.builder().name("Tordesillas").id("8").coords(Coords.builder().latitude(41.310278).longitude(-4.975278).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("8")).findFirst().orElse(null)).imageUrl("https://abrasador.com/wp-content/uploads/2024/01/5-Cosas-que-ver-en-Tordesillas.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Candeleda").id("9").coords(Coords.builder().latitude(40.208611).longitude(-5.3075).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("9")).findFirst().orElse(null)).imageUrl("https://media-cdn.tripadvisor.com/media/photo-c/1280x250/0d/93/d0/2e/piscinas-naturales-candeleda.jpg").province(leon).build(),
                    VillageEntity.builder().name("Aguasal").id("10").coords(Coords.builder().latitude(41.3040932127772).longitude(-4.626361159).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("10")).findFirst().orElse(null)).imageUrl("https://www.mapa.gob.es/images/es/dsc_0330_a_tcm30-556517.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Aguilar de Campos").id("11").coords(Coords.builder().latitude(41.9762697026253).longitude(-5.1966922789).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("11")).findFirst().orElse(null)).imageUrl("https://static.wixstatic.com/media/be2270_fbf3be35ba8c4b4d9437a42c3a39187f~mv2.jpg/v1/fill/w_497,h_332,al_c,q_80,enc_auto/be2270_fbf3be35ba8c4b4d9437a42c3a39187f~mv2.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Adalia").id("12").coords(Coords.builder().latitude(41.6438088287139).longitude(-5.1263019774).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("12")).findFirst().orElse(null)).imageUrl("https://s3.ppllstatics.com/elnortedecastilla/www/multimedia/202005/25/media/cortadas/Imagen%20Iglesia%20del%20Salvador%20(2)-k1qG--624x385@El%20Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Alaejos").id("15").coords(Coords.builder().latitude(41.3073713272509).longitude(-5.2174956654).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("13")).findFirst().orElse(null)).imageUrl("https://www.turismocastillayleon.com/es/patrimonio-cultura/alaejos.ficheros/267611-hq_Alaejos01_Valladolid.jpg/h,267611-hq_Alaejos01_Valladolid.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Arroyo de la Encomienda").id("21").coords(Coords.builder().latitude(41.6247643815669).longitude(-4.7922456571).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("14")).findFirst().orElse(null)).imageUrl("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Arroyo_de_la_Encomienda%2C_La_Flecha%2C_Plaza_de_Espa%C3%B1a%2C_Ayuntamiento_1.jpg/320px-Arroyo_de_la_Encomienda%2C_La_Flecha%2C_Plaza_de_Espa%C3%B1a%2C_Ayuntamiento_1.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Ataquines").id("22").coords(Coords.builder().latitude(41.1852529705255).longitude(-4.7756640226).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("15")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/f/0/1600/28620.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Bahabon").id("23").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("16")).findFirst().orElse(null)).imageUrl("https://upload.wikimedia.org/wikipedia/commons/9/91/Iglesia_de_Bahab%C3%B3n.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Adalia").id("12").coords(Coords.builder().latitude(41.6438088287139).longitude(-5.1263019774).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("17")).findFirst().orElse(null)).imageUrl("https://media2.clubrural.com/img500x180/pueblos/valladolid/gallegos-de-hornija/20160219143040-valladolid-gallegos-de-hornija.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Aguasal").id("13").coords(Coords.builder().latitude(41.3040932127772).longitude(-4.626361159).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("18")).findFirst().orElse(null)).imageUrl("https://vivetupueblo.es/wp-content/uploads/2020/08/Aguasal.-Valladolid.-Castilla-y-Leon.-Calle.-7.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Aguilar de Campos").id("14").coords(Coords.builder().latitude(41.9762697026253).longitude(-5.1966922789).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("19")).findFirst().orElse(null)).imageUrl("https://1.bp.blogspot.com/-piFXc2N4nAU/VK8RVy-HvzI/AAAAAAAAAMA/_mkFqvuxn7o/s1600/Aguilar%2Bde%2BCampos_Aytº.%2B[1280x768].JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Alaejos").id("15").coords(Coords.builder().latitude(41.3073713272509).longitude(-5.2174956654).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("20")).findFirst().orElse(null)).imageUrl("https://destinocastillayleon.es/index/wp-content/uploads/2013/04/b0afe6f8a97facaf7d848f4860384c5a.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Alcazaren").id("16").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("21")).findFirst().orElse(null)).imageUrl("https://live.staticflickr.com/4013/4646811161_75b7997a6a_z.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Aldea de San Miguel").id("17").coords(Coords.builder().latitude(41.4457841943164).longitude(-4.6115167303).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("22")).findFirst().orElse(null)).imageUrl("https://4.bp.blogspot.com/-j-owuwwzG9Y/VLB5TDeQwHI/AAAAAAAAAQM/lm2Mkpqlei8/s1600/Aldea%2Bde%2BSan%2BMiguel%2B-%2BIglesia%2BParroquial%2Bde%2BSan%2BMiguel%2BArcangel_%2BS.XII-XV-XVIII%2B(11)%2B[1280x768].JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Aldeamayor de San Martin").id("18").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("23")).findFirst().orElse(null)).imageUrl("https://4.bp.blogspot.com/-Ul97yN_vsT0/VLE-c7F8bfI/AAAAAAAAATI/fbPq_0b1PTQ/s1600/Aldeamayor%2Bde%2BSan%2BMartín_Ayuntamiento%2By%2BPlaza%2BMayor%2B[1280x768].JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Almenara de Adaja").id("19").coords(Coords.builder().latitude(41.2071466103346).longitude(-4.6799801076).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("24")).findFirst().orElse(null)).imageUrl("https://live.staticflickr.com/3468/3404550090_fb1563345a_b.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Amusquillo").id("20").coords(Coords.builder().latitude(41.7506158813509).longitude(-4.2901800697).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("25")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/corner-main/39/288/7874.jpg?1391495413").province(valladolid).build(),
                    VillageEntity.builder().name("Arroyo de la Encomienda").id("21").coords(Coords.builder().latitude(41.6247643815669).longitude(-4.7922456571).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("26")).findFirst().orElse(null)).imageUrl("https://3.bp.blogspot.com/-v7BcR2ThmD4/U5ZIyImg-ZI/AAAAAAAAv84/Pb4eM0NRZd8/s1600/IMG_6772.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Ataquines").id("22").coords(Coords.builder().latitude(41.1852529705255).longitude(-4.7756640226).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("27")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/f/0/1600/28620.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("Bahabon").id("23").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("28")).findFirst().orElse(null)).imageUrl("https://cdn.horariodemisas.com/wp-content/uploads/2020/10/parroquia-de-nuestra-senora-de-la-asuncion-bahabon-de-valcorba-2048x1371.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Barcial de la Loma").id("24").coords(Coords.builder().latitude(41.95412592339).longitude(-5.279930550125).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("29")).findFirst().orElse(null)).imageUrl("https://photo980x880.mnstatic.com/faa752a66f29e0bf8a3b5f4ab74b5a06/la-iglesia-1720461.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Barruelo del Valle").id("25").coords(Coords.builder().latitude(41.6751050124769).longitude(-5.0845655979).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("30")).findFirst().orElse(null)).imageUrl("https://cdn.pixabay.com/photo/2019/07/15/06/50/barruelo-del-valle-4338672_1280.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Becilla de Valderaduey").id("26").coords(Coords.builder().latitude(42.0976102087316).longitude(-5.2045977027).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("31")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des-main/143/960/28624.jpg?1629635453").province(valladolid).build(),
                    VillageEntity.builder().name("Benafarces").id("27").coords(Coords.builder().latitude(41.6212175756859).longitude(-5.2789506929).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("32")).findFirst().orElse(null)).imageUrl("https://s3.ppllstatics.com/elnortedecastilla/www/multimedia/202206/14/media/cortadas/benafarces1-k44H-U1704055994433PI-1968x1216@El Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Bercero").id("28").coords(Coords.builder().latitude(41.5584761250053).longitude(-5.072501904).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("33")).findFirst().orElse(null)).imageUrl("http://3.bp.blogspot.com/-lZMlhKuGLSw/VMg3Oa4K3BI/AAAAAAAAAhM/ZblRGeWt_Yk/s1600/Bercero_Ermita%2Bdel%2BCristo%2Bdel%2BHumilladero%2B[1280x768]_fhdr.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Berceruelo").id("29").coords(Coords.builder().latitude(41.5907018011593).longitude(-5.0169526654).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("34")).findFirst().orElse(null)).imageUrl("http://www.absolutvalladolid.com/wp-content/uploads/2010/06/Berceruelo.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Berrueces").id("30").coords(Coords.builder().latitude(41.9505147032558).longitude(-5.0965679158).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("35")).findFirst().orElse(null)).imageUrl("https://lh3.googleusercontent.com/p/AF1QipN-COY2AbxhS_yeCEfiCTIB0PnkVApQfXyasTAf=s1600-h768").province(valladolid).build(),
                    VillageEntity.builder().name("Bobadilla del Campo").id("31").coords(Coords.builder().latitude(41.1813472317549).longitude(-5.0354943446).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("36")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/a/f/1600/28629.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("Bocigas").id("32").coords(Coords.builder().latitude(41.24336607488).longitude(-4.686725825204).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("37")).findFirst().orElse(null)).imageUrl("https://www.absolutvalladolid.com/wp-content/uploads/2011/03/Bocigas.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Bocos de Duero").id("33").coords(Coords.builder().latitude(41.6211609753566).longitude(-4.0587457057).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("38")).findFirst().orElse(null)).imageUrl("http://topriberadelduero.com/sites/default/files/alojamiento-bocos-duero-valladolid.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Boecillo").id("34").coords(Coords.builder().latitude(41.5389094260949).longitude(-4.7266046314).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("39")).findFirst().orElse(null)).imageUrl("http://www.fotopaises.com/Fotos-Paises/t/2007/9/21/499_1190379722.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Bolanos de Campos").id("35").coords(Coords.builder().latitude(42.013783403256).longitude(-5.27453245652).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("40")).findFirst().orElse(null)).imageUrl("https://imagenes.diariodevalladolid.es/files/vertical_image_414/uploads/2024/04/17/661ff66569399.jpeg").province(valladolid).build(),
                    VillageEntity.builder().name("Brahojos de Medina").id("36").coords(Coords.builder().latitude(41.221979349715).longitude(-5.04444258417).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("41")).findFirst().orElse(null)).imageUrl("https://media2.clubrural.com/img990x400/pueblos/valladolid/brahojos-de-medina/20160218181920-valladolid-brahojos-de-medina.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Bustillo de Chaves").id("37").coords(Coords.builder().latitude(42.1248958189153).longitude(-5.108424048).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("42")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/e/6/1600/28634.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("Cabezon de Pisuerga").id("38").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("43")).findFirst().orElse(null)).imageUrl("https://fotografias.antena3.com/clipping/cmsimages02/2022/04/27/7E38C62D-C715-4173-9638-16325B880CA1/puente-cabezon-pisuerga_98.jpg?crop=3648,2052,x0,y344&amp;width=1900&amp;height=1069&amp;optimize=low&amp;format=webply").province(valladolid).build(),
                    VillageEntity.builder().name("Cabezon de Valderaduey").id("39").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("44")).findFirst().orElse(null)).imageUrl("https://s1.ppllstatics.com/elnortedecastilla/www/multimedia/2023/04/24/cabezon2-kj9C-U200136341584wvE-1200x840@ElNorte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Cabreros del Monte").id("40").coords(Coords.builder().latitude(41.844715221929).longitude(-5.28440147511).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("45")).findFirst().orElse(null)).imageUrl("http://3.bp.blogspot.com/-wLTpSSwecqo/VNqp_-GgfrI/AAAAAAAAAtg/-pdMwW1kxC8/s1600/Cabreros%2Bdel%2BMonte_Iglesia%2BParroquial%2Bde%2BSan%2BJuan%2BBautista%2B[1024x768].jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Campaspero").id("41").coords(Coords.builder().latitude(41.5011044287228).longitude(-4.2251893317).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("46")).findFirst().orElse(null)).imageUrl("https://fotos.hoteles.net/articulos/campaspero-turismo-valladolid-4413-1.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Campillo El").id("42").coords(Coords.builder().latitude(37.6922172748497).longitude(-6.6417620247).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("47")).findFirst().orElse(null)).imageUrl("https://media2.clubrural.com/img990x400/pueblos/valladolid/el-campillo/20160218200535-valladolid-el-campillo.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Esguevillas de Esgueva").id("43").coords(Coords.builder().latitude(41.7533698198745).longitude(-4.3751444797).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("48")).findFirst().orElse(null)).imageUrl("https://www.biodiversidadvirtual.org/etno/data/media/29/Iglesia-de-Esguevillas-de-Esgueva-(Valladolid)-72523.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fombellida").id("44").coords(Coords.builder().latitude(41.749569778988).longitude(-4.18805011851).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("49")).findFirst().orElse(null)).imageUrl("https://www.hernandezrabal.com/espana/castillaleon/valladolid/vdfonigl.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fompedraza").id("45").coords(Coords.builder().latitude(41.5185685944398).longitude(-4.1446783669).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("50")).findFirst().orElse(null)).imageUrl("https://vasdepuebloenpueblo.files.wordpress.com/2015/06/iglesia-de-san-bartolome-iii.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fontihoyuelo").id("46").coords(Coords.builder().latitude(42.168710754076).longitude(-5.05438760987).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("151")).findFirst().orElse(null)).imageUrl("https://s2.ppllstatics.com/elnortedecastilla/www/multimedia/202207/03/media/cortadas/fontiyoyuelo2-kM8H-U170555963782K8F-1248x770@El Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fresno el Viejo").id("47").coords(Coords.builder().latitude(41.180412206643).longitude(-5.16445348322).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("152")).findFirst().orElse(null)).imageUrl("https://www.cyltv.es/media/imagenesf/197039c0-eeec-3db5-eb60aed2c5842e23.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fuensaldana").id("48").coords(Coords.builder().latitude(41.7130890195157).longitude(-4.7458438517).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("153")).findFirst().orElse(null)).imageUrl("https://s1.ppllstatics.com/elnortedecastilla/www/multimedia/202207/05/media/cortadas/fuensaldana1-kb3D-U170556138921EFE-1248x770@El Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Fuente el Sol").id("49").coords(Coords.builder().latitude(41.1721514067333).longitude(-4.9327304661).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("154")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/3/5/1600/28669.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("Fuente Olmedo").id("50").coords(Coords.builder().latitude(41.2497748134535).longitude(-4.6409573222).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("155")).findFirst().orElse(null)).imageUrl("https://2.bp.blogspot.com/-chQbVrKr6T8/VUVulRWVGlI/AAAAAAAABdk/wBiEhaf5me0/s1600/Fuente%2BOlmedo%2B_%2BIglesia%2BParroquial%2Bde%2BSan%2BJuan%2BEvangelista_S.XVII-XVIII%2B(5)%2B(Copiar).JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Pozuelo de la Orden").id("51").coords(Coords.builder().latitude(41.8120270199803).longitude(-5.2689412335).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("156")).findFirst().orElse(null)).imageUrl("https://static3.elnortedecastilla.es/www/multimedia/202208/04/media/cortadas/pozuelo1-kYEG-U170734832261cFI-984x608@El Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Puras").id("52").coords(Coords.builder().latitude(41.1867586015765).longitude(-4.6645917636).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("157")).findFirst().orElse(null)).imageUrl("https://i.ytimg.com/vi/7yLn2m6kFJI/maxresdefault.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Quintanilla de Arriba").id("53").coords(Coords.builder().latitude(41.6078015847766).longitude(-4.2555825844).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("158")).findFirst().orElse(null)).imageUrl("http://topriberadelduero.com/sites/default/files/visitar-pueblo-quintanilla-arriba.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Quintanilla de Onesimo").id("54").coords(Coords.builder().latitude(41.6066462974517).longitude(-4.3535238672).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("159")).findFirst().orElse(null)).imageUrl("https://www.tuscasasrurales.com/img-guias-viaje/valladolid/quintanilla-de-onesimo/max/iglesia-de-san-emiliano.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Quintanilla de Trigueros").id("55").coords(Coords.builder().latitude(41.8691325687146).longitude(-4.656705102).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("160")).findFirst().orElse(null)).imageUrl("https://farm5.static.flickr.com/4058/5123354877_7ece4397c0.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Quintanilla del Molar").id("56").coords(Coords.builder().latitude(41.9913672638276).longitude(-5.4591118366).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("161")).findFirst().orElse(null)).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/guia-cf/ubicacion/localidad/imagenes/media-filer_public-5b-74-5b74bd4b-9a05-41dc-a219-98d639ae011c-plaza_mayort.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Rabano").id("57").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("162")).findFirst().orElse(null)).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/guia-cf/ubicacion/localidad/imagenes/media-filer_public-c7-49-c7493009-c3b4-492a-ab7e-0a8aa0ded5b4-riot.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Ramiro").id("58").coords(Coords.builder().latitude(41.2330500314386).longitude(-4.7836233165).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("163")).findFirst().orElse(null)).imageUrl("https://alchetron.com/cdn/ramiro-valladolid-074c0f29-0747-4469-bc47-fa35ba3d182-resize-750.jpeg").province(valladolid).build(),
                    VillageEntity.builder().name("Renedo de Esgueva").id("59").coords(Coords.builder().latitude(41.6497177275247).longitude(-4.6263058119).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("164")).findFirst().orElse(null)).imageUrl("https://s2.ppllstatics.com/elnortedecastilla/www/multimedia/202106/30/media/cortadas/mun-renedo-1-kwqB-U140714863405AeF-1968x1216@El Norte.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Roales de Campos").id("60").coords(Coords.builder().latitude(42.0574669835704).longitude(-5.4856477444).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("165")).findFirst().orElse(null)).imageUrl("https://4.bp.blogspot.com/-WBfxpqEmMgk/VsET7BPVN_I/AAAAAAAAFG0/Sj6AhVwxQfM/s1600/Roales_Iglesia%2BParroquial%2Bde%2BSan%2BMiguel_S.XVIII%2B%25283%2529%2B%2528Copiar%2529.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Robladillo").id("61").coords(Coords.builder().latitude(41.6096233703386).longitude(-4.9042853873).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("166")).findFirst().orElse(null)).imageUrl("https://static2.elnortedecastilla.es/www/multimedia/202112/19/media/MM-nobelen-robladillo/belen-robladillo33.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Roturas").id("62").coords(Coords.builder().latitude(41.6703418316765).longitude(-4.1078342801).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("167")).findFirst().orElse(null)).imageUrl("https://live.staticflickr.com/1568/25675046994_d6aaeda26c_b.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Rubi de Bracamonte").id("63").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("168")).findFirst().orElse(null)).imageUrl("https://bosquedelcamarate.es/wp-content/uploads/2023/10/que-ver-en-rubi-de-bracamonte-provincia-de-valladolid.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Rueda").id("64").coords(Coords.builder().latitude(41.4140583196883).longitude(-4.9891428724).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("169")).findFirst().orElse(null)).imageUrl("https://camerlust.com/wp-content/uploads/2021/03/Plaza-Mayor-rueda.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Saelices de Mayorga").id("65").coords(Coords.builder().latitude(42.2136809866875).longitude(-5.2092352321).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("170")).findFirst().orElse(null)).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/guia-cf/ubicacion/localidad/imagenes/media-filer_public-e6-7b-e67b47be-2afc-407e-9b12-6bdaf901191d-san_pedro_y_aytot.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Salvador de Zapardiel").id("66").coords(Coords.builder().latitude(41.1424166181846).longitude(-4.8628845893).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("171")).findFirst().orElse(null)).imageUrl("https://media2.clubrural.com/img500x180/pueblos/avila/castellanos-de-zapardiel/20160219011053-avila-castellanos-de-zapardiel.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Cebrian de Mazote").id("67").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("172")).findFirst().orElse(null)).imageUrl("http://1.bp.blogspot.com/-6rOaNrkgStM/U16Mtui6KPI/AAAAAAAAq6w/4RAZzCu_mbo/s1600/IMG_9435.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("San Llorente").id("68").coords(Coords.builder().latitude(41.6898394298587).longitude(-4.0689367317).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("173")).findFirst().orElse(null)).imageUrl("https://static.wixstatic.com/media/be2270_235c08a58fb44d5f9b1eb58b5a9bc8df~mv2.jpg/v1/fill/w_1000,h_665,al_c,q_90,usm_0.66_1.00_0.01/be2270_235c08a58fb44d5f9b1eb58b5a9bc8df~mv2.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Martin de Valveni").id("69").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("174")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/1/e/1600/28752.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("San Miguel del Arroyo").id("70").coords(Coords.builder().latitude(41.4427082871185).longitude(-4.4748433265).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("175")).findFirst().orElse(null)).imageUrl("https://2.bp.blogspot.com/-yc4I_9lBKNM/VunclTucqiI/AAAAAAAAFS4/P158zyrUktY9zjcqqE65hEKndFXZxJ9QQ/s1600/San%2BMiguel%2Bdel%2BArroyo_Ermita%2Bdel%2BSanto%2BCristo%2B%2528Copiar%2529.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("San Miguel del Pino").id("71").coords(Coords.builder().latitude(41.515154655399).longitude(-4.90904079351).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("176")).findFirst().orElse(null)).imageUrl("https://www.krisporelmundo.com/wp-content/uploads/2023/11/San-Miguel-del-Pino-Valladolid-2-1024x768.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Pablo de la Moraleja").id("72").coords(Coords.builder().latitude(41.1580176896067).longitude(-4.7734350479).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("177")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/a/b/1600/28755.jpg#google").province(valladolid).build(),
                    VillageEntity.builder().name("San Pedro de Latarce").id("73").coords(Coords.builder().latitude(41.7390965215224).longitude(-5.33757685).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("178")).findFirst().orElse(null)).imageUrl("https://2.bp.blogspot.com/-GVhYls2D27U/V6C5A9cMxzI/AAAAAAAAQjg/CHj1rxTWI1wHll-i9D8Q4jtT-vG3nzUXwCLcB/s1600/DSC03683.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("San Pelayo").id("74").coords(Coords.builder().latitude(41.6893062967451).longitude(-5.0258115139).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("179")).findFirst().orElse(null)).imageUrl("https://photo980x880.mnstatic.com/7d9701560ce56ac7478196615b9752e7/la-fuente-1612801.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Roman de Hornija").id("75").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("180")).findFirst().orElse(null)).imageUrl("http://live.staticflickr.com/65535/50311409253_fdb55ea0b2_o.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Salvador").id("76").coords(Coords.builder().latitude(41.6190265452418).longitude(-5.0760774087).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("181")).findFirst().orElse(null)).imageUrl("https://thumbs.dreamstime.com/z/view-church-san-salvador-valladolid-spain-valladolid-spain-may-view-church-san-salvador-valladolid-153855578.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("San Vicente del Palacio").id("77").coords(Coords.builder().latitude(41.2298732653377).longitude(-4.8814660724).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("182")).findFirst().orElse(null)).imageUrl("https://www.absolutvalladolid.com/wp-content/uploads/2011/06/San-Vicente-del-Palacio-300x206.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Santa Eufemia del Arroyo").id("78").coords(Coords.builder().latitude(41.896760124385).longitude(-5.27447755948).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("183")).findFirst().orElse(null)).imageUrl("https://2.bp.blogspot.com/-5BMyaUlGIOE/Vv2fx-Bmb6I/AAAAAAAAFiM/uKij4lsbQLoOTUZ4Ns61m_CtY3Z7RdKWA/s1600/Santa%2BEufemia%2Bdel%2BArroyo_Iglesia%2Bde%2BSta%2BEufemia%2B%25282%2529%2B%2528Copiar%2529.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Santervas de Campos").id("79").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("184")).findFirst().orElse(null)).imageUrl("https://www.absolutvalladolid.com/wp-content/uploads/2010/07/Santervás-de-Campos-300x225.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Santibanez de Valcorba").id("80").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("185")).findFirst().orElse(null)).imageUrl("https://live.staticflickr.com/3393/3500483253_ccdbeb6e81.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Santovenia de Pisuerga").id("81").coords(Coords.builder().latitude(41.7015678988589).longitude(-4.6711295187).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("186")).findFirst().orElse(null)).imageUrl("https://3.bp.blogspot.com/-xKnv-gTAJKk/Vv8LFEpLy8I/AAAAAAAAFoQ/xIE3kEnvXmgijRIagvo6DZcyjeEE7Leag/s1600/Santovenia%2Bde%2BPisuerga%2B_Iglesia%2Bde%2BSan%2Bjuan_2006%2B%2528Copiar%2529.JPG").province(valladolid).build(),
                    VillageEntity.builder().name("Sardon de Duero").id("82").coords(Coords.builder().latitude(41.6529473).longitude(-4.7283877).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("187")).findFirst().orElse(null)).imageUrl("https://bosquedelcamarate.es/wp-content/uploads/2023/10/que-ver-en-sardon-de-duero-provincia-de-valladolid-scaled.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Seca La").id("83").coords(Coords.builder().latitude(41.4423922158098).longitude(-4.9169983629).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("188")).findFirst().orElse(null)).imageUrl("https://www.guiarepsol.com/content/dam/repsol-guia/guia-cf/ubicacion/localidad/imagenes/media-filer_public-42-c0-42c06fa3-954d-47ea-a7d8-be1797c8ead2-2-_plaza.jpg").province(valladolid).build(),
                    VillageEntity.builder().name("Serrada").id("84").coords(Coords.builder().latitude(41.4689989093089).longitude(-4.8531726357).build()).festivity(festivitiesEntities.stream().filter(festivity -> festivity.getId().equals("189")).findFirst().orElse(null)).imageUrl("https://ucmedia.er2.co/es/des/8/b/1600/28765.jpg#google").province(valladolid).build()
            );


            villageRepository.saveAll(villages);
            log.info("Villages loaded successfully");
        };
    }
}
